// ============================================================================
// Hello World Plugin — Example for OpenChat Plugin System
// ============================================================================
//
// Install: copy this folder to ~/.openchat/plugins/hello-world/
//
// Each tool's execute() receives:
//   - input: parsed JSON matching the inputSchema in manifest.json
//   - ctx: { workingDirectory, sessionId }
//
// Must return: { success: boolean, output: string, error?: string }
//

export default {
  tools: {
    greet: {
      async execute(input, ctx) {
        const name = input.name || 'World';
        return {
          success: true,
          output: `Hello, ${name}! 👋\nThis message was generated by the hello-world plugin.\nWorking directory: ${ctx.workingDirectory}`,
        };
      },
    },
  },
};
